# Generated by Django 5.2 on 2025-05-04 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livo', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_started', '🕓 Not Started'), ('in_progress', '⚙️ In Progress'), ('completed', '✅ Completed'), ('cancelled', '❌ Cancelled')], default='not_started', max_length=20),
        ),
    ]
